apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: product-service
  name: product-service
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: product-service
  type: LoadBalancer