name: Docker Build Deploy





on:



  push:



    branches: [master]





env:



PROJECT: ${{ secrets.PROJECT }}



CLUSTER: product-service



ZONE: us-central1



DEPLOYMENT_NAME: product-service





jobs:



  build:



    runs-on:



      ubuntu-latest








  permissions:



    contents: "read"



    id-token: "write"





    steps:



      - uses: actions/checkout@v3



      - name: run shell script



        run: echo commit hash is ${{ github.sha }}



      - name: Login to Docker Hub



        uses: docker/login-action@v1



        with:



          username: ${{ secrets.USERNAME }}



          password: ${{ secrets.TOKEN }}



      - name: Build the Docker image



        run: docker build . --file Dockerfile --tag my-image-name:${{ github.sha }}



      - name: Build and push



        uses: docker/build-push-action@v2



        with:



          context: .



          file: ./Dockerfile



          push: true



          tags: ${{ secrets.USERNAME }}/product-service:${{ github.sha }}



      - name: Update config files in k8s



        run: sed -i.bak 's/{{tag}}/${{ github.sha }}/g' k8s/deploy.yaml && rm k8s/*.bak






      - id: "auth"



        uses: "google-github-actions/auth@v0"



        with:



          credentials_json: "${{ secrets.CREDENTIALS }}"





      - name: Set up Cloud SDK



        uses: google-github-actions/setup-gcloud@v0





      - name: "Use gcloud CLI"



        run: "gcloud info"









      - run: |-



          gcloud container clusters get-credentials "$CLUSTER" --zone "$ZONE"







      - name: Deploy



        run: |-



          kubectl apply -f k8s/deploy.yaml



          kubectl rollout status deployment/$DEPLOYMENT_NAME



          kubectl get services -o wide